#!/bin/bash

#######################
### Cleanup Script ####
#######################
#### Version 0.9.3 ####
#######################
# Changes: Merged changes from Torqu3Wr3nch
# @author Torqu3Wr3nch
# @url https://github.com/Torqu3Wr3nch/unraid_rclone_mount/blob/umountFix/rclone_unmount

# REQUIRED SETTINGS

# Copy settings from rclone_mount
# NOTE: This only handles one mount instance. If you have multiple rclone
#       mounts, add manual entries for each mount.

RcloneRemoteName="gdrive_media_vfs" # Name of rclone remote mount WITHOUT ':'.
RcloneMountShare="/mnt/user/cloud/rcloneVFS"
LocalFilesShare="/mnt/user/cloud/cache"
RcloneCacheShare="/mnt/user0/cloud/rcloneVFS"
MergerfsMountShare="/mnt/user/cloud/media"

# END SETTINGS

echo "$(date "+%d.%m.%Y %T") INFO: *** Starting rclone_cleanup script ***"

####### Unmount Rclone #######

umount -l $MergerfsMountShare/$RcloneRemoteName
umount -l $RcloneMountShare/$RcloneRemoteName
umount -l $RcloneCacheShare/cache/$RcloneRemoteName
umount -l $LocalFilesShare/$RcloneRemoteName

####### Cleanup Tracking Files #######

echo "$(date "+%d.%m.%Y %T") INFO: *** Removing Tracking Files ***"

find /mnt/user/appdata/rclone/remotes -name dockers_started* -delete
find /mnt/user/appdata/rclone/remotes -name mount_running* -delete
find /mnt/user/appdata/rclone/remotes -name upload_running* -delete
echo "$(date "+%d.%m.%Y %T") INFO: ***Finished Cleanup! ***"

exit
